# generated by datamodel-codegen:
#   filename:  filtered-openapi.yaml
#   timestamp: 2025-04-24T22:29:35+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Literal, Optional, Union
from uuid import UUID

from pydantic import BaseModel, Field, conint, constr


class ErrorResponse(BaseModel):
    error: str
    message: str


class ImageRequest(BaseModel):
    prompt: str = Field(
        ..., description='Required. The prompt to use to generate the image.'
    )
    aspect_ratio: Optional[str] = Field(
        None,
        description="Optional. The aspect ratio (e.g., 'ASPECT_16_9', 'ASPECT_1_1'). Cannot be used with resolution. Defaults to 'ASPECT_1_1' if unspecified.",
    )
    model: str = Field(..., description="The model used (e.g., 'V_2', 'V_2A_TURBO')")
    magic_prompt_option: Optional[str] = Field(
        None, description="Optional. MagicPrompt usage ('AUTO', 'ON', 'OFF')."
    )
    seed: Optional[int] = Field(
        None,
        description='Optional. A number between 0 and 2147483647.',
        ge=0,
        le=2147483647,
    )
    style_type: Optional[str] = Field(
        None,
        description="Optional. Style type ('AUTO', 'GENERAL', 'REALISTIC', 'DESIGN', 'RENDER_3D', 'ANIME'). Only for models V_2 and above.",
    )
    negative_prompt: Optional[str] = Field(
        None,
        description='Optional. Description of what to exclude. Only for V_1, V_1_TURBO, V_2, V_2_TURBO.',
    )
    num_images: Optional[int] = Field(
        1,
        description='Optional. Number of images to generate (1-8). Defaults to 1.',
        ge=1,
        le=8,
    )
    resolution: Optional[str] = Field(
        None,
        description="Optional. Resolution (e.g., 'RESOLUTION_1024_1024'). Only for model V_2. Cannot be used with aspect_ratio.",
    )
    color_palette: Optional[Dict[str, Any]] = Field(
        None, description='Optional. Color palette object. Only for V_2, V_2_TURBO.'
    )


class IdeogramGenerateRequest(BaseModel):
    image_request: ImageRequest = Field(
        ..., description='The image generation request parameters.'
    )


class IdeogramGenerateRequest(BaseModel):
    image_request: ImageRequest = Field(
        ..., description='The image generation request parameters.'
    )


class Datum(BaseModel):
    prompt: Optional[str] = Field(
        None, description='The prompt used to generate this image.'
    )
    resolution: Optional[str] = Field(
        None, description="The resolution of the generated image (e.g., '1024x1024')."
    )
    is_image_safe: Optional[bool] = Field(
        None, description='Indicates whether the image is considered safe.'
    )
    seed: Optional[int] = Field(
        None, description='The seed value used for this generation.'
    )
    url: Optional[str] = Field(None, description='URL to the generated image.')
    style_type: Optional[str] = Field(
        None,
        description="The style type used for generation (e.g., 'REALISTIC', 'ANIME').",
    )


class IdeogramGenerateResponse(BaseModel):
    created: Optional[datetime] = Field(
        None, description='Timestamp when the generation was created.'
    )
    data: Optional[List[Datum]] = Field(
        None, description='Array of generated image information.'
    )


class Code(Enum):
    int_1100 = 1100
    int_1101 = 1101
    int_1102 = 1102
    int_1103 = 1103


class RenderingSpeed1(str, Enum):
    TURBO = 'TURBO'
    DEFAULT = 'DEFAULT'
    QUALITY = 'QUALITY'


class KlingErrorResponse(BaseModel):
    code: int = Field(
        ..., description='Error code value as defined in the API documentation'
    )
    message: str = Field(..., description='Human-readable error message')
    request_id: str = Field(
        ..., description='Request ID for tracking and troubleshooting'
    )


class KlingVideoExtendResponse(BaseModel):
    code: Optional[int] = Field(None, description='Error code')
    message: Optional[str] = Field(None, description='Error message')
    request_id: Optional[str] = Field(None, description='Request ID')
    data: Optional[Data2] = None


class KlingLipSyncInputObject(BaseModel):
    video_id: Optional[str] = Field(
        None,
        description='The ID of the video generated by Kling AI. Only supports 5-second and 10-second videos generated within the last 30 days.',
    )
    video_url: Optional[str] = Field(
        None,
        description='Get link for uploaded video. Video files support .mp4/.mov, file size does not exceed 100MB, video length between 2-10s.',
    )
    mode: KlingLipSyncMode
    text: Optional[str] = Field(
        None,
        description='Text Content for Lip-Sync Video Generation. Required when mode is text2video. Maximum length is 120 characters.',
    )
    voice_id: Optional[str] = Field(
        None,
        description='Voice ID. Required when mode is text2video. The system offers a variety of voice options to choose from.',
    )
    voice_language: Optional[KlingLipSyncVoiceLanguage] = 'en'
    voice_speed: Optional[float] = Field(
        1,
        description='Speech Rate. Valid range: 0.8~2.0, accurate to one decimal place.',
        ge=0.8,
        le=2.0,
    )
    audio_type: Optional[KlingAudioUploadType] = None
    audio_file: Optional[str] = Field(
        None,
        description='Local Path of Audio File. Supported formats: .mp3/.wav/.m4a/.aac, maximum file size of 5MB. Base64 code.',
    )
    audio_url: Optional[str] = Field(
        None,
        description='Audio File Download URL. Supported formats: .mp3/.wav/.m4a/.aac, maximum file size of 5MB.',
    )


class KlingLipSyncRequest(BaseModel):
    input: KlingLipSyncInputObject
    callback_url: Optional[AnyUrl] = Field(
        None,
        description='The callback notification address. Server will notify when the task status changes.',
    )


class Data3(BaseModel):
    task_id: Optional[str] = Field(None, description='Task ID')
    task_status: Optional[KlingTaskStatus] = None
    task_info: Optional[TaskInfo] = None
    created_at: Optional[int] = Field(None, description='Task creation time')
    updated_at: Optional[int] = Field(None, description='Task update time')
    task_result: Optional[TaskResult] = None


class KlingLipSyncResponse(BaseModel):
    code: Optional[int] = Field(None, description='Error code')
    message: Optional[str] = Field(None, description='Error message')
    request_id: Optional[str] = Field(None, description='Request ID')
    data: Optional[Data3] = None


class KlingSingleImageEffectInput(BaseModel):
    model_name: KlingSingleImageEffectModelName
    image: str = Field(
        ...,
        description='Reference Image. URL or Base64 encoded string (without data:image prefix). File size cannot exceed 10MB, resolution not less than 300*300px, aspect ratio between 1:2.5 ~ 2.5:1.',
    )
    duration: KlingSingleImageEffectDuration


class KlingDualCharacterEffectInput(BaseModel):
    model_name: Optional[KlingCharacterEffectModelName] = 'kling-v1'
    mode: Optional[KlingVideoGenMode] = 'std'
    images: KlingDualCharacterImages
    duration: KlingVideoGenDuration


class Data4(BaseModel):
    task_id: Optional[str] = Field(None, description='Task ID')
    task_status: Optional[KlingTaskStatus] = None
    task_info: Optional[TaskInfo] = None
    created_at: Optional[int] = Field(None, description='Task creation time')
    updated_at: Optional[int] = Field(None, description='Task update time')
    task_result: Optional[TaskResult] = None


class KlingVideoEffectsResponse(BaseModel):
    code: Optional[int] = Field(None, description='Error code')
    message: Optional[str] = Field(None, description='Error message')
    request_id: Optional[str] = Field(None, description='Request ID')
    data: Optional[Data4] = None


class KlingImageGenerationsRequest(BaseModel):
    model_name: Optional[KlingImageGenModelName] = 'kling-v1'
    prompt: str = Field(..., description='Positive text prompt', max_length=500)
    negative_prompt: Optional[str] = Field(
        None, description='Negative text prompt', max_length=200
    )
    image: Optional[str] = Field(
        None, description='Reference Image - Base64 encoded string or image URL'
    )
    image_reference: Optional[KlingImageGenImageReferenceType] = None
    image_fidelity: Optional[float] = Field(
        0.5, description='Reference intensity for user-uploaded images', ge=0.0, le=1.0
    )
    human_fidelity: Optional[float] = Field(
        0.45, description='Subject reference similarity', ge=0.0, le=1.0
    )
    n: Optional[int] = Field(1, description='Number of generated images', ge=1, le=9)
    aspect_ratio: Optional[KlingImageGenAspectRatio] = '16:9'
    callback_url: Optional[AnyUrl] = Field(
        None, description='The callback notification address'
    )


class TaskResult5(BaseModel):
    images: Optional[List[KlingImageResult]] = None


class Data5(BaseModel):
    task_id: Optional[str] = Field(None, description='Task ID')
    task_status: Optional[KlingTaskStatus] = None
    task_status_msg: Optional[str] = Field(None, description='Task status information')
    created_at: Optional[int] = Field(None, description='Task creation time')
    updated_at: Optional[int] = Field(None, description='Task update time')
    task_result: Optional[TaskResult5] = None


class KlingImageGenerationsResponse(BaseModel):
    code: Optional[int] = Field(None, description='Error code')
    message: Optional[str] = Field(None, description='Error message')
    request_id: Optional[str] = Field(None, description='Request ID')
    data: Optional[Data5] = None


class KlingVirtualTryOnRequest(BaseModel):
    model_name: Optional[KlingVirtualTryOnModelName] = 'kolors-virtual-try-on-v1'
    human_image: str = Field(
        ..., description='Reference human image - Base64 encoded string or image URL'
    )
    cloth_image: Optional[str] = Field(
        None,
        description='Reference clothing image - Base64 encoded string or image URL',
    )
    callback_url: Optional[AnyUrl] = Field(
        None, description='The callback notification address'
    )


class Data6(BaseModel):
    task_id: Optional[str] = Field(None, description='Task ID')
    task_status: Optional[KlingTaskStatus] = None
    task_status_msg: Optional[str] = Field(None, description='Task status information')
    created_at: Optional[int] = Field(None, description='Task creation time')
    updated_at: Optional[int] = Field(None, description='Task update time')
    task_result: Optional[TaskResult5] = None


class KlingVirtualTryOnResponse(BaseModel):
    code: Optional[int] = Field(None, description='Error code')
    message: Optional[str] = Field(None, description='Error message')
    request_id: Optional[str] = Field(None, description='Request ID')
    data: Optional[Data6] = None


class KlingRequestError(KlingErrorResponse):
    code: Optional[Code2] = Field(
        None,
        description='- 1200: Invalid request parameters\n- 1201: Invalid parameters\n- 1202: Invalid request method\n- 1203: Requested resource does not exist\n',
    )


class Code3(Enum):
    int_5000 = 5000
    int_5001 = 5001
    int_5002 = 5002


class KlingServerError(KlingErrorResponse):
    code: Optional[Code3] = Field(
        None,
        description='- 5000: Internal server error\n- 5001: Service temporarily unavailable\n- 5002: Server internal timeout\n',
    )


class Code4(Enum):
    int_1300 = 1300
    int_1301 = 1301
    int_1302 = 1302
    int_1303 = 1303
    int_1304 = 1304


class KlingStrategyError(KlingErrorResponse):
    code: Optional[Code4] = Field(
        None,
        description='- 1300: Trigger platform strategy\n- 1301: Trigger content security policy\n- 1302: API request too frequent\n- 1303: Concurrency/QPS exceeds limit\n- 1304: Trigger IP whitelist policy\n',
    )


class MinimaxBaseResponse(BaseModel):
    status_code: int = Field(
        ...,
        description='Status code. 0 indicates success, other values indicate errors.',
    )
    status_msg: str = Field(
        ..., description='Specific error details or success message.'
    )


class File(BaseModel):
    bytes: Optional[int] = Field(None, description='File size in bytes')
    created_at: Optional[int] = Field(
        None, description='Unix timestamp when the file was created, in seconds'
    )
    download_url: Optional[str] = Field(
        None, description='The URL to download the video'
    )
    file_id: Optional[int] = Field(None, description='Unique identifier for the file')
    filename: Optional[str] = Field(None, description='The name of the file')
    purpose: Optional[str] = Field(None, description='The purpose of using the file')


class MinimaxFileRetrieveResponse(BaseModel):
    base_resp: MinimaxBaseResponse
    file: File


class Status(str, Enum):
    Queueing = 'Queueing'
    Preparing = 'Preparing'
    Processing = 'Processing'
    Success = 'Success'
    Fail = 'Fail'


class MinimaxTaskResultResponse(BaseModel):
    base_resp: MinimaxBaseResponse
    file_id: Optional[str] = Field(
        None,
        description='After the task status changes to Success, this field returns the file ID corresponding to the generated video.',
    )
    status: Status = Field(
        ...,
        description="Task status: 'Queueing' (in queue), 'Preparing' (task is preparing), 'Processing' (generating), 'Success' (task completed successfully), or 'Fail' (task failed).",
    )
    task_id: str = Field(..., description='The task ID being queried.')


class Model(str, Enum):
    T2V_01_Director = 'T2V-01-Director'
    I2V_01_Director = 'I2V-01-Director'
    S2V_01 = 'S2V-01'
    I2V_01 = 'I2V-01'
    I2V_01_live = 'I2V-01-live'
    T2V_01 = 'T2V-01'


class SubjectReferenceItem(BaseModel):
    image: Optional[str] = Field(
        None, description='URL or base64 encoding of the subject reference image.'
    )
    mask: Optional[str] = Field(
        None,
        description='URL or base64 encoding of the mask for the subject reference image.',
    )


class MinimaxVideoGenerationRequest(BaseModel):
    callback_url: Optional[str] = Field(
        None,
        description='Optional. URL to receive real-time status updates about the video generation task.',
    )
    first_frame_image: Optional[str] = Field(
        None,
        description='URL or base64 encoding of the first frame image. Required when model is I2V-01, I2V-01-Director, or I2V-01-live.',
    )
    model: Model = Field(
        ...,
        description='Required. ID of model. Options: T2V-01-Director, I2V-01-Director, S2V-01, I2V-01, I2V-01-live, T2V-01',
    )
    prompt: Optional[constr(max_length=2000)] = Field(
        None,
        description='Description of the video. Should be less than 2000 characters. Supports camera movement instructions in [brackets].',
    )
    prompt_optimizer: Optional[bool] = Field(
        True,
        description='If true (default), the model will automatically optimize the prompt. Set to false for more precise control.',
    )
    subject_reference: Optional[List[SubjectReferenceItem]] = Field(
        None,
        description='Only available when model is S2V-01. The model will generate a video based on the subject uploaded through this parameter.',
    )


class MinimaxVideoGenerationResponse(BaseModel):
    base_resp: MinimaxBaseResponse
    task_id: str = Field(
        ..., description='The task ID for the asynchronous video generation task.'
    )


class Data7(BaseModel):
    code: Optional[int] = Field(None, description='Error code; 0 indicates success')
    msg: Optional[str] = Field(None, description='Error information')
    resource_pack_subscribe_infos: Optional[List[ResourcePackSubscribeInfo]] = Field(
        None, description='Resource package list'
    )


class KlingResourcePackageResponse(BaseModel):
    code: Optional[int] = Field(None, description='Error code; 0 indicates success')
    message: Optional[str] = Field(None, description='Error information')
    request_id: Optional[str] = Field(
        None,
        description='Request ID, generated by the system, used to track requests and troubleshoot problems',
    )
    data: Optional[Data7] = None


class Object(str, Enum):
    event = 'event'


class Type(str, Enum):
    payment_intent_succeeded = 'payment_intent.succeeded'


class StripeRequestInfo(BaseModel):
    id: Optional[str] = None
    idempotency_key: Optional[str] = None


class Object1(str, Enum):
    payment_intent = 'payment_intent'


class StripeAmountDetails(BaseModel):
    tip: Optional[Dict[str, Any]] = None


class Object2(str, Enum):
    charge = 'charge'


class StripeAddress(BaseModel):
    city: Optional[str] = None
    country: Optional[str] = None
    line1: Optional[str] = None
    line2: Optional[str] = None
    postal_code: Optional[str] = None
    state: Optional[str] = None


class StripeOutcome(BaseModel):
    advice_code: Optional[Any] = None
    network_advice_code: Optional[Any] = None
    network_decline_code: Optional[Any] = None
    network_status: Optional[str] = None
    reason: Optional[Any] = None
    risk_level: Optional[str] = None
    risk_score: Optional[int] = None
    seller_message: Optional[str] = None
    type: Optional[str] = None


class Checks(BaseModel):
    address_line1_check: Optional[Any] = None
    address_postal_code_check: Optional[Any] = None
    cvc_check: Optional[str] = None


class ExtendedAuthorization(BaseModel):
    status: Optional[str] = None


class IncrementalAuthorization(BaseModel):
    status: Optional[str] = None


class Multicapture(BaseModel):
    status: Optional[str] = None


class NetworkToken(BaseModel):
    used: Optional[bool] = None


class Overcapture(BaseModel):
    maximum_amount_capturable: Optional[int] = None
    status: Optional[str] = None


class StripeCardDetails(BaseModel):
    amount_authorized: Optional[int] = None
    authorization_code: Optional[Any] = None
    brand: Optional[str] = None
    checks: Optional[Checks] = None
    country: Optional[str] = None
    exp_month: Optional[int] = None
    exp_year: Optional[int] = None
    extended_authorization: Optional[ExtendedAuthorization] = None
    fingerprint: Optional[str] = None
    funding: Optional[str] = None
    incremental_authorization: Optional[IncrementalAuthorization] = None
    installments: Optional[Any] = None
    last4: Optional[str] = None
    mandate: Optional[Any] = None
    multicapture: Optional[Multicapture] = None
    network: Optional[str] = None
    network_token: Optional[NetworkToken] = None
    network_transaction_id: Optional[str] = None
    overcapture: Optional[Overcapture] = None
    regulated_status: Optional[str] = None
    three_d_secure: Optional[Any] = None
    wallet: Optional[Any] = None


class StripeRefundList(BaseModel):
    object: Optional[str] = None
    data: Optional[List[Dict[str, Any]]] = None
    has_more: Optional[bool] = None
    total_count: Optional[int] = None
    url: Optional[str] = None


class Card(BaseModel):
    installments: Optional[Any] = None
    mandate_options: Optional[Any] = None
    network: Optional[Any] = None
    request_three_d_secure: Optional[str] = None


class StripePaymentMethodOptions(BaseModel):
    card: Optional[Card] = None


class StripeShipping(BaseModel):
    address: Optional[StripeAddress] = None
    carrier: Optional[str] = None
    name: Optional[str] = None
    phone: Optional[str] = None
    tracking_number: Optional[str] = None


class Model(str, Enum):
    T2V_01_Director = 'T2V-01-Director'
    I2V_01_Director = 'I2V-01-Director'
    S2V_01 = 'S2V-01'
    I2V_01 = 'I2V-01'
    I2V_01_live = 'I2V-01-live'
    T2V_01 = 'T2V-01'


class SubjectReferenceItem(BaseModel):
    image: Optional[str] = Field(
        None, description='URL or base64 encoding of the subject reference image.'
    )
    mask: Optional[str] = Field(
        None,
        description='URL or base64 encoding of the mask for the subject reference image.',
    )


class MinimaxVideoGenerationRequest(BaseModel):
    model: Model = Field(
        ...,
        description='Required. ID of model. Options: T2V-01-Director, I2V-01-Director, S2V-01, I2V-01, I2V-01-live, T2V-01',
    )
    prompt: Optional[str] = Field(
        None,
        description='Description of the video. Should be less than 2000 characters. Supports camera movement instructions in [brackets].',
        max_length=2000,
    )
    prompt_optimizer: Optional[bool] = Field(
        True,
        description='If true (default), the model will automatically optimize the prompt. Set to false for more precise control.',
    )
    first_frame_image: Optional[str] = Field(
        None,
        description='URL or base64 encoding of the first frame image. Required when model is I2V-01, I2V-01-Director, or I2V-01-live.',
    )
    subject_reference: Optional[List[SubjectReferenceItem]] = Field(
        None,
        description='Only available when model is S2V-01. The model will generate a video based on the subject uploaded through this parameter.',
    )
    callback_url: Optional[str] = Field(
        None,
        description='Optional. URL to receive real-time status updates about the video generation task.',
    )


class MinimaxBaseResponse(BaseModel):
    status_code: int = Field(
        ...,
        description='Status code. 0 indicates success, other values indicate errors.',
    )
    status_msg: str = Field(
        ..., description='Specific error details or success message.'
    )


class MinimaxVideoGenerationResponse(BaseModel):
    task_id: str = Field(
        ..., description='The task ID for the asynchronous video generation task.'
    )
    base_resp: MinimaxBaseResponse


class File(BaseModel):
    file_id: Optional[int] = Field(None, description='Unique identifier for the file')
    bytes: Optional[int] = Field(None, description='File size in bytes')
    created_at: Optional[int] = Field(
        None, description='Unix timestamp when the file was created, in seconds'
    )
    filename: Optional[str] = Field(None, description='The name of the file')
    purpose: Optional[str] = Field(None, description='The purpose of using the file')
    download_url: Optional[str] = Field(
        None, description='The URL to download the video'
    )


class MinimaxFileRetrieveResponse(BaseModel):
    file: File
    base_resp: MinimaxBaseResponse


class Status1(str, Enum):
    Queueing = 'Queueing'
    Preparing = 'Preparing'
    Processing = 'Processing'
    Success = 'Success'
    Fail = 'Fail'


class MinimaxTaskResultResponse(BaseModel):
    task_id: str = Field(..., description='The task ID being queried.')
    status: Status1 = Field(
        ...,
        description="Task status: 'Queueing' (in queue), 'Preparing' (task is preparing), 'Processing' (generating), 'Success' (task completed successfully), or 'Fail' (task failed).",
    )
    file_id: Optional[str] = Field(
        None,
        description='After the task status changes to Success, this field returns the file ID corresponding to the generated video.',
    )
    base_resp: MinimaxBaseResponse


class OutputFormat(str, Enum):
    jpeg = 'jpeg'
    png = 'png'


class BFLFluxPro11GenerateRequest(BaseModel):
    prompt: str = Field(..., description='The main text prompt for image generation')
    image_prompt: Optional[str] = Field(None, description='Optional image prompt')
    width: int = Field(..., description='Width of the generated image')
    height: int = Field(..., description='Height of the generated image')
    prompt_upsampling: Optional[bool] = Field(
        None, description='Whether to use prompt upsampling'
    )
    seed: Optional[int] = Field(None, description='Random seed for reproducibility')
    safety_tolerance: Optional[int] = Field(None, description='Safety tolerance level')
    output_format: Optional[OutputFormat] = Field(
        None, description='Output image format'
    )
    webhook_url: Optional[str] = Field(
        None, description='Optional webhook URL for async processing'
    )
    webhook_secret: Optional[str] = Field(
        None, description='Optional webhook secret for async processing'
    )


class BFLFluxPro11GenerateResponse(BaseModel):
    id: str = Field(..., description='Job ID for tracking')
    polling_url: str = Field(..., description='URL to poll for results')


class BFLFluxProGenerateRequest(BaseModel):
    prompt: str = Field(..., description='The text prompt for image generation.')
    negative_prompt: Optional[str] = Field(
        None, description='The negative prompt for image generation.'
    )
    width: int = Field(
        ..., description='The width of the image to generate.', ge=64, le=2048
    )
    height: int = Field(
        ..., description='The height of the image to generate.', ge=64, le=2048
    )
    num_inference_steps: Optional[int] = Field(
        None, description='The number of inference steps.', ge=1, le=100
    )
    guidance_scale: Optional[float] = Field(
        None, description='The guidance scale for generation.', ge=1.0, le=20.0
    )
    seed: Optional[int] = Field(None, description='The seed value for reproducibility.')
    num_images: Optional[int] = Field(
        None, description='The number of images to generate.', ge=1, le=4
    )


class BFLFluxProGenerateResponse(BaseModel):
    id: str = Field(..., description='The unique identifier for the generation task.')
    polling_url: str = Field(..., description='URL to poll for the generation result.')


class Steps(RootModel[int]):
    root: int = Field(
        ...,
        description='Number of steps for the image generation process',
        examples=[50],
        ge=15,
        le=50,
        title='Steps',
    )


class Guidance(RootModel[float]):
    root: float = Field(
        ...,
        description='Guidance strength for the image generation process',
        ge=1.5,
        le=100.0,
        title='Guidance',
    )


class WebhookUrl(RootModel[AnyUrl]):
    root: AnyUrl = Field(
        ..., description='URL to receive webhook notifications', title='Webhook Url'
    )


class BFLAsyncResponse(BaseModel):
    id: str = Field(..., title='Id')
    polling_url: str = Field(..., title='Polling Url')


class BFLAsyncWebhookResponse(BaseModel):
    id: str = Field(..., title='Id')
    status: str = Field(..., title='Status')
    webhook_url: str = Field(..., title='Webhook Url')


class Top(RootModel[int]):
    root: int = Field(
        ...,
        description='Number of pixels to expand at the top of the image',
        ge=0,
        le=2048,
        title='Top',
    )


class Bottom(RootModel[int]):
    root: int = Field(
        ...,
        description='Number of pixels to expand at the bottom of the image',
        ge=0,
        le=2048,
        title='Bottom',
    )


class Left(RootModel[int]):
    root: int = Field(
        ...,
        description='Number of pixels to expand on the left side of the image',
        ge=0,
        le=2048,
        title='Left',
    )


class Right(RootModel[int]):
    root: int = Field(
        ...,
        description='Number of pixels to expand on the right side of the image',
        ge=0,
        le=2048,
        title='Right',
    )


class CannyLowThreshold(RootModel[int]):
    root: int = Field(
        ...,
        description='Low threshold for Canny edge detection',
        ge=0,
        le=500,
        title='Canny Low Threshold',
    )


class CannyHighThreshold(RootModel[int]):
    root: int = Field(
        ...,
        description='High threshold for Canny edge detection',
        ge=0,
        le=500,
        title='Canny High Threshold',
    )


class Steps2(RootModel[int]):
    root: int = Field(
        ...,
        description='Number of steps for the image generation process',
        ge=15,
        le=50,
        title='Steps',
    )


class Guidance2(RootModel[float]):
    root: float = Field(
        ...,
        description='Guidance strength for the image generation process',
        ge=1.0,
        le=100.0,
        title='Guidance',
    )


class BFLOutputFormat(str, Enum):
    jpeg = 'jpeg'
    png = 'png'


class BFLValidationError(BaseModel):
    loc: List[Union[str, int]] = Field(..., title='Location')
    msg: str = Field(..., title='Message')
    type: str = Field(..., title='Error Type')


class Datum2(BaseModel):
    image_id: Optional[str] = Field(
        None, description='Unique identifier for the generated image'
    )
    url: Optional[str] = Field(None, description='URL to access the generated image')


class RecraftImageGenerationResponse(BaseModel):
    created: int = Field(
        ..., description='Unix timestamp when the generation was created'
    )
    credits: int = Field(..., description='Number of credits used for the generation')
    data: List[Datum2] = Field(..., description='Array of generated image information')


class RecraftImageFeatures(BaseModel):
    nsfw_score: Optional[float] = None


class RecraftTextLayoutItem(BaseModel):
    bbox: List[List[float]]
    text: str


class RecraftImageColor(BaseModel):
    rgb: Optional[List[int]] = None
    std: Optional[List[float]] = None
    weight: Optional[float] = None


class RecraftImageStyle(str, Enum):
    digital_illustration = 'digital_illustration'
    icon = 'icon'
    realistic_image = 'realistic_image'
    vector_illustration = 'vector_illustration'


class RecraftImageSubStyle(str, Enum):
    field_2d_art_poster = '2d_art_poster'
    field_3d = '3d'
    field_80s = '80s'
    glow = 'glow'
    grain = 'grain'
    hand_drawn = 'hand_drawn'
    infantile_sketch = 'infantile_sketch'
    kawaii = 'kawaii'
    pixel_art = 'pixel_art'
    psychedelic = 'psychedelic'
    seamless = 'seamless'
    voxel = 'voxel'
    watercolor = 'watercolor'
    broken_line = 'broken_line'
    colored_outline = 'colored_outline'
    colored_shapes = 'colored_shapes'
    colored_shapes_gradient = 'colored_shapes_gradient'
    doodle_fill = 'doodle_fill'
    doodle_offset_fill = 'doodle_offset_fill'
    offset_fill = 'offset_fill'
    outline = 'outline'
    outline_gradient = 'outline_gradient'
    uneven_fill = 'uneven_fill'
    field_70s = '70s'
    cartoon = 'cartoon'
    doodle_line_art = 'doodle_line_art'
    engraving = 'engraving'
    flat_2 = 'flat_2'
    kawaii_1 = 'kawaii'
    line_art = 'line_art'
    linocut = 'linocut'
    seamless_1 = 'seamless'
    b_and_w = 'b_and_w'
    enterprise = 'enterprise'
    hard_flash = 'hard_flash'
    hdr = 'hdr'
    motion_blur = 'motion_blur'
    natural_light = 'natural_light'
    studio_portrait = 'studio_portrait'
    line_circuit = 'line_circuit'
    field_2d_art_poster_2 = '2d_art_poster_2'
    engraving_color = 'engraving_color'
    flat_air_art = 'flat_air_art'
    hand_drawn_outline = 'hand_drawn_outline'
    handmade_3d = 'handmade_3d'
    stickers_drawings = 'stickers_drawings'
    plastic = 'plastic'
    pictogram = 'pictogram'


class RecraftTransformModel(str, Enum):
    refm1 = 'refm1'
    recraft20b = 'recraft20b'
    recraftv2 = 'recraftv2'
    recraftv3 = 'recraftv3'
    flux1_1pro = 'flux1_1pro'
    flux1dev = 'flux1dev'
    imagen3 = 'imagen3'
    hidream_i1_dev = 'hidream_i1_dev'


class RecraftImageFormat(str, Enum):
    webp = 'webp'
    png = 'png'


class RecraftResponseFormat(str, Enum):
    url = 'url'
    b64_json = 'b64_json'


class RecraftImage(BaseModel):
    b64_json: Optional[str] = None
    features: Optional[RecraftImageFeatures] = None
    image_id: UUID
    revised_prompt: Optional[str] = None
    url: Optional[str] = None


class RecraftUserControls(BaseModel):
    artistic_level: Optional[int] = None
    background_color: Optional[RecraftImageColor] = None
    colors: Optional[List[RecraftImageColor]] = None
    no_text: Optional[bool] = None


class RecraftTextLayout(RootModel[List[RecraftTextLayoutItem]]):
    root: List[RecraftTextLayoutItem]


class RecraftProcessImageRequest(BaseModel):
    image: StrictBytes
    image_format: Optional[RecraftImageFormat] = None
    response_format: Optional[RecraftResponseFormat] = None


class RecraftProcessImageResponse(BaseModel):
    created: int
    credits: int
    image: RecraftImage


class RecraftImageToImageRequest(BaseModel):
    block_nsfw: Optional[bool] = None
    calculate_features: Optional[bool] = None
    controls: Optional[RecraftUserControls] = None
    image: StrictBytes
    image_format: Optional[RecraftImageFormat] = None
    model: Optional[RecraftTransformModel] = None
    n: Optional[int] = None
    negative_prompt: Optional[str] = None
    prompt: str
    random_seed: Optional[int] = None
    response_format: Optional[RecraftResponseFormat] = None
    strength: float
    style: Optional[RecraftImageStyle] = None
    style_id: Optional[UUID] = None
    substyle: Optional[RecraftImageSubStyle] = None
    text_layout: Optional[RecraftTextLayout] = None


class RecraftGenerateImageResponse(BaseModel):
    created: int
    credits: int
    data: List[RecraftImage]


class RecraftTransformImageWithMaskRequest(BaseModel):
    block_nsfw: Optional[bool] = None
    calculate_features: Optional[bool] = None
    image: StrictBytes
    image_format: Optional[RecraftImageFormat] = None
    mask: StrictBytes
    model: Optional[RecraftTransformModel] = None
    n: Optional[int] = None
    negative_prompt: Optional[str] = None
    prompt: str
    random_seed: Optional[int] = None
    response_format: Optional[RecraftResponseFormat] = None
    style: Optional[RecraftImageStyle] = None
    style_id: Optional[UUID] = None
    substyle: Optional[RecraftImageSubStyle] = None
    text_layout: Optional[RecraftTextLayout] = None


class KlingErrorResponse(BaseModel):
    code: int = Field(
        ...,
        description='- 1000: Authentication failed\n- 1001: Authorization is empty\n- 1002: Authorization is invalid\n- 1003: Authorization is not yet valid\n- 1004: Authorization has expired\n- 1100: Account exception\n- 1101: Account in arrears (postpaid scenario)\n- 1102: Resource pack depleted or expired (prepaid scenario)\n- 1103: Unauthorized access to requested resource\n- 1200: Invalid request parameters\n- 1201: Invalid parameters\n- 1202: Invalid request method\n- 1203: Requested resource does not exist\n- 1300: Trigger platform strategy\n- 1301: Trigger content security policy\n- 1302: API request too frequent\n- 1303: Concurrency/QPS exceeds limit\n- 1304: Trigger IP whitelist policy\n- 5000: Internal server error\n- 5001: Service temporarily unavailable\n- 5002: Server internal timeout\n',
    )
    message: str = Field(..., description='Human-readable error message')
    request_id: str = Field(
        ..., description='Request ID for tracking and troubleshooting'
    )


class LumaAspectRatio(str, Enum):
    field_1_1 = '1:1'
    field_16_9 = '16:9'
    field_9_16 = '9:16'
    field_4_3 = '4:3'
    field_3_4 = '3:4'
    field_21_9 = '21:9'
    field_9_21 = '9:21'


class LumaVideoModel(str, Enum):
    ray_2 = 'ray-2'
    ray_flash_2 = 'ray-flash-2'
    ray_1_6 = 'ray-1-6'


class LumaVideoModelOutputResolution1(str, Enum):
    field_540p = '540p'
    field_720p = '720p'
    field_1080p = '1080p'
    field_4k = '4k'


class LumaVideoModelOutputResolution(
    RootModel[Union[LumaVideoModelOutputResolution1, str]]
):
    root: Union[LumaVideoModelOutputResolution1, str]


class LumaVideoModelOutputDuration1(str, Enum):
    field_5s = '5s'
    field_9s = '9s'


class LumaVideoModelOutputDuration(
    RootModel[Union[LumaVideoModelOutputDuration1, str]]
):
    root: Union[LumaVideoModelOutputDuration1, str]


class LumaImageModel(str, Enum):
    photon_1 = 'photon-1'
    photon_flash_1 = 'photon-flash-1'


class LumaImageRef(BaseModel):
    url: Optional[AnyUrl] = Field(None, description='The URL of the image reference')
    weight: Optional[float] = Field(
        None, description='The weight of the image reference'
    )


class LumaImageIdentity(BaseModel):
    images: Optional[List[AnyUrl]] = Field(
        None, description='The URLs of the image identity'
    )


class LumaModifyImageRef(BaseModel):
    url: Optional[AnyUrl] = Field(None, description='The URL of the image reference')
    weight: Optional[float] = Field(
        None, description='The weight of the modify image reference'
    )


class Type1(str, Enum):
    generation = 'generation'


class LumaGenerationReference(BaseModel):
    type: Literal['generation']
    id: UUID = Field(..., description='The ID of the generation')


class Type2(str, Enum):
    image = 'image'


class LumaImageReference(BaseModel):
    type: Literal['image']
    url: AnyUrl = Field(..., description='The URL of the image')


class LumaKeyframe(RootModel[Union[LumaGenerationReference, LumaImageReference]]):
    root: Union[LumaGenerationReference, LumaImageReference] = Field(
        ...,
        description='A keyframe can be either a Generation reference, an Image, or a Video',
        discriminator='type',
    )


class LumaGenerationType(str, Enum):
    video = 'video'
    image = 'image'


class LumaState(str, Enum):
    queued = 'queued'
    dreaming = 'dreaming'
    completed = 'completed'
    failed = 'failed'


class LumaAssets(BaseModel):
    video: Optional[AnyUrl] = Field(None, description='The URL of the video')
    image: Optional[AnyUrl] = Field(None, description='The URL of the image')
    progress_video: Optional[AnyUrl] = Field(
        None, description='The URL of the progress video'
    )


class GenerationType(str, Enum):
    video = 'video'


class GenerationType1(str, Enum):
    image = 'image'


class CharacterRef(BaseModel):
    identity0: Optional[LumaImageIdentity] = None


class LumaImageGenerationRequest(BaseModel):
    generation_type: Optional[GenerationType1] = 'image'
    model: Optional[LumaImageModel] = 'photon-1'
    prompt: Optional[str] = Field(None, description='The prompt of the generation')
    aspect_ratio: Optional[LumaAspectRatio] = '16:9'
    callback_url: Optional[AnyUrl] = Field(
        None, description='The callback URL for the generation'
    )
    image_ref: Optional[List[LumaImageRef]] = None
    style_ref: Optional[List[LumaImageRef]] = None
    character_ref: Optional[CharacterRef] = None
    modify_image_ref: Optional[LumaModifyImageRef] = None


class GenerationType2(str, Enum):
    upscale_video = 'upscale_video'


class LumaUpscaleVideoGenerationRequest(BaseModel):
    generation_type: Optional[GenerationType2] = 'upscale_video'
    resolution: Optional[LumaVideoModelOutputResolution] = None
    callback_url: Optional[AnyUrl] = Field(
        None, description='The callback URL for the upscale'
    )


class GenerationType3(str, Enum):
    add_audio = 'add_audio'


class LumaAudioGenerationRequest(BaseModel):
    generation_type: Optional[GenerationType3] = 'add_audio'
    prompt: Optional[str] = Field(None, description='The prompt of the audio')
    negative_prompt: Optional[str] = Field(
        None, description='The negative prompt of the audio'
    )
    callback_url: Optional[AnyUrl] = Field(
        None, description='The callback URL for the audio'
    )


class LumaError(BaseModel):
    detail: Optional[str] = Field(None, description='The error message')


class AspectRatio(str, Enum):
    field_16_9 = '16:9'
    field_4_3 = '4:3'
    field_1_1 = '1:1'
    field_3_4 = '3:4'
    field_9_16 = '9:16'


class Duration(int, Enum):
    integer_5 = 5
    integer_8 = 8


class Model1(str, Enum):
    v3_5 = 'v3.5'


class MotionMode(str, Enum):
    normal = 'normal'
    fast = 'fast'


class OpenAIImageEditRequest(BaseModel):
    background: Optional[str] = Field(
        None, description='Background transparency', examples=['opaque']
    )
    model: str = Field(
        ..., description='The model to use for image editing', examples=['gpt-image-1']
    )
    moderation: Optional[Moderation] = Field(
        None, description='Content moderation setting', examples=['auto']
    )
    n: Optional[int] = Field(
        None, description='The number of images to generate', examples=[1]
    )
    output_compression: Optional[int] = Field(
        None, description='Compression level for JPEG or WebP (0-100)', examples=[100]
    )
    output_format: Optional[OutputFormat] = Field(
        None, description='Format of the output image', examples=['png']
    )
    prompt: str = Field(
        ...,
        description='A text description of the desired edit',
        examples=['Give the rocketship rainbow coloring'],
    )
    quality: Optional[str] = Field(
        None, description='The quality of the edited image', examples=['low']
    )
    size: Optional[str] = Field(
        None, description='Size of the output image', examples=['1024x1024']
    )
    user: Optional[str] = Field(
        None,
        description='Video generation status codes:\n* 1 - Generation successful\n* 5 - Generating\n* 6 - Deleted\n* 7 - Contents moderation failed\n* 8 - Generation failed\n',
    )
    style: Optional[str] = None
    url: Optional[str] = None


class PixverseVideoResultResponse(BaseModel):
    ErrCode: Optional[int] = None
    ErrMsg: Optional[str] = None
    Resp: Optional[Resp2] = None


class Image(BaseModel):
    bytesBase64Encoded: str
    gcsUri: Optional[str] = None
    mimeType: Optional[str] = None


class Image1(BaseModel):
    bytesBase64Encoded: Optional[str] = None
    gcsUri: str
    mimeType: Optional[str] = None


class Instance(BaseModel):
    prompt: str = Field(..., description='Text description of the video')
    image: Optional[Union[Image, Image1]] = Field(
        None, description='Optional image to guide video generation'
    )


class Background(str, Enum):
    transparent = 'transparent'
    opaque = 'opaque'


class Quality(str, Enum):
    low = 'low'
    medium = 'medium'
    high = 'high'
    standard = 'standard'
    hd = 'hd'


class OutputFormat1(str, Enum):
    png = 'png'
    webp = 'webp'
    jpeg = 'jpeg'


class Moderation(str, Enum):
    low = 'low'
    auto = 'auto'


class Background(str, Enum):
    transparent = 'transparent'
    opaque = 'opaque'


class ResponseFormat(str, Enum):
    url = 'url'
    b64_json = 'b64_json'


class Style3(str, Enum):
    vivid = 'vivid'
    natural = 'natural'


class OpenAIImageGenerationRequest(BaseModel):
    model: Optional[str] = Field(
        None, description='The model to use for image generation', examples=['dall-e-3']
    )
    prompt: str = Field(
        ...,
        description='A text description of the desired image',
        examples=['Draw a rocket in front of a blackhole in deep space'],
    )
    quality: Optional[Quality] = Field(
        None, description='The quality of the generated image', examples=['high']
    )
    quality: Optional[Quality3] = Field(
        None, description='The quality of the generated image', examples=['high']
    )
    size: Optional[str] = Field(
        None,
        description='Size of the image (e.g., 1024x1024, 1536x1024, auto)',
        examples=['1024x1536'],
    )
    output_format: Optional[OutputFormat1] = Field(
        None, description='Format of the output image', examples=['png']
    )
    output_compression: Optional[int] = Field(
        None, description='Compression level for JPEG or WebP (0-100)', examples=[100]
    )
    moderation: Optional[Moderation] = Field(
        None, description='Content moderation setting', examples=['auto']
    )
    background: Optional[Background] = Field(
        None, description='Background transparency', examples=['opaque']
    )
    response_format: Optional[ResponseFormat] = Field(
        None, description='Response format of image data', examples=['b64_json']
    )
    style: Optional[Style3] = Field(
        None, description='Style of the image (only for dall-e-3)', examples=['vivid']
    )
    user: Optional[str] = Field(
        None,
        description='A unique identifier for end-user monitoring',
        examples=['user-1234'],
    )


class OpenAIImageEditRequest(BaseModel):
    model: str = Field(
        ..., description='The model to use for image editing', examples=['gpt-image-1']
    )
    prompt: str = Field(
        ...,
        description='A text description of the desired edit',
        examples=['Give the rocketship rainbow coloring'],
    )
    n: Optional[int] = Field(
        None, description='The number of images to generate', examples=[1]
    )
    quality: Optional[str] = Field(
        None, description='The quality of the edited image', examples=['low']
    )
    size: Optional[str] = Field(
        None, description='Size of the output image', examples=['1024x1024']
    )
    output_format: Optional[OutputFormat1] = Field(
        None, description='Format of the output image', examples=['png']
    )
    output_compression: Optional[int] = Field(
        None, description='Compression level for JPEG or WebP (0-100)', examples=[100]
    )
    moderation: Optional[Moderation] = Field(
        None, description='Content moderation setting', examples=['auto']
    )
    background: Optional[str] = Field(
        None, description='Background transparency', examples=['opaque']
    )
    user: Optional[str] = Field(
        None,
        description='A unique identifier for end-user monitoring',
        examples=['user-1234'],
    )


class OpenAIImageGenerationResponse(BaseModel):
    data: Optional[List[Datum1]] = None


class KlingAccountError(KlingErrorResponse):
    code: Optional[Code] = Field(
        None,
        description='- 1100: Account exception\n- 1101: Account in arrears (postpaid scenario)\n- 1102: Resource pack depleted or expired (prepaid scenario)\n- 1103: Unauthorized access to requested resource\n',
    )


class KlingAuthenticationError(KlingErrorResponse):
    code: Optional[Code1] = Field(
        None,
        description='- 1000: Authentication failed\n- 1001: Authorization is empty\n- 1002: Authorization is invalid\n- 1003: Authorization is not yet valid\n- 1004: Authorization has expired\n',
    )
