pretrained_model_name_or_path = "F:/sd/ComfyUI-aki-v1.4/ComfyUI-aki-v1.4/models/unet/anima_baseV10.safetensors"
vae = "F:/sd/ComfyUI-aki-v1.4/ComfyUI-aki-v1.4/models/vae/Qwen_Image-VAE.safetensors"
qwen3 = "F:/sd/ComfyUI-aki-v1.4/ComfyUI-aki-v1.4/models/unet/qwen_2.5_vl_7b_fp8_scaled.safetensors"
qwen3_max_token_length = 512
t5_max_token_length = 512
timestep_sampling = "shift"
sigmoid_scale = 1.0
discrete_flow_shift = 3.0
weighting_scheme = "uniform"
attn_mode = "xformers"
train_data_dir = "F:/lyb"
prior_loss_weight = 1
resolution = "1024,1024"
enable_bucket = true
min_bucket_reso = 256
max_bucket_reso = 2048
bucket_reso_steps = 64
bucket_no_upscale = true
output_name = "laoyb-1536*2-anima-lokr"
output_dir = "./output"
save_model_as = "safetensors"
save_precision = "bf16"
save_every_n_epochs = 1
max_train_epochs = 40
train_batch_size = 3
gradient_accumulation_steps = 1
network_train_unet_only = true
learning_rate = 1
unet_lr = 1
text_encoder_lr = 1
lr_scheduler = "constant"
lr_warmup_steps = 0
loss_type = "l1"
optimizer_type = "Prodigy"
network_dim = 64
network_alpha = 32
network_module = "lycoris.kohya"
log_with = "tensorboard"
logging_dir = "./logs"
caption_extension = ".txt"
keep_tokens = 0
prefer_json_caption = true
seed = 1337
clip_skip = 2
mixed_precision = "bf16"
full_bf16 = true
no_half_vae = true
cache_latents = true
cache_latents_to_disk = true
cache_text_encoder_outputs = true
cache_text_encoder_outputs_to_disk = true
max_data_loader_n_workers = 0
sample_at_first = true
network_args = ["algo=lokr", "factor=-1", "preset=F:/SD-Trainer-v2.2.0/SD-Trainer/config/lycoris_anima_preset.toml"]
optimizer_args = ["decouple=True", "weight_decay=0.01", "use_bias_correction=True", "d_coef=2.0"]
sample_prompts = "F:\\SD-Trainer-v2.2.0\\SD-Trainer\\config\\autosave\\20260521-105322-promopt.txt"
