enable_conv = false

unet_target_module = [
  "Block",
  "PatchEmbed",
  "TimestepEmbedding",
  "FinalLayer",
  "LLMAdapterTransformerBlock",
]
unet_target_name = []

text_encoder_target_module = [
  "Qwen3Attention",
  "Qwen3MLP",
  "Qwen3SdpaAttention",
  "Qwen3FlashAttention2",
]
text_encoder_target_name = []
