"""ComfyUI-independent V53 gallery provider contract."""

from .capabilities import all_provider_capabilities, get_provider_capabilities
from .contracts import (
    autocomplete_client_query_key,
    browse_client_query_key,
    error_envelope,
    facet_client_query_key,
    page_key,
    success_envelope,
    validate_browse_request,
    validate_autocomplete_request,
    validate_facet_request,
)
from .cursor import CursorCodecError, CursorPayload, OpaqueCursorCodec
from .domain import (
    CONTRACT_VERSION,
    AvailabilityState,
    AutocompleteRequest,
    BrowseRequest,
    ContractValidationError,
    ErrorCode,
    FacetPage,
    FacetRequest,
    FeatureState,
    Fidelity,
    PeriodSemantics,
    ProviderCapabilities,
    ProviderError,
    ProviderPage,
    ProviderPayloadError,
    ProviderRuntime,
    Source,
    View,
)
from .providers import GalleryProvider, LegacyProviderAdapter
from .live_providers import (
    CIVITAI_API_ROOT,
    CivitaiLiveProvider,
    DanbooruLiveProvider,
    GelbooruLiveProvider,
    LiveProviderRegistry,
    ProviderRequestError,
    YandereLiveProvider,
    build_live_provider_registry,
)
from .routes import (
    FEATURE_API_PATH,
    V2_API_ROOT,
    create_feature_handler,
    create_v2_handlers,
    get_default_cursor_codec,
    register_feature_route,
    register_v2_routes,
)
from .settings import FeatureFlagConfigurationError, V53FeatureFlags, load_v53_feature_flags

__all__ = [
    "CONTRACT_VERSION",
    "AvailabilityState",
    "AutocompleteRequest",
    "BrowseRequest",
    "CIVITAI_API_ROOT",
    "CivitaiLiveProvider",
    "ContractValidationError",
    "CursorCodecError",
    "CursorPayload",
    "DanbooruLiveProvider",
    "ErrorCode",
    "FacetPage",
    "FacetRequest",
    "FeatureState",
    "FeatureFlagConfigurationError",
    "FEATURE_API_PATH",
    "Fidelity",
    "GalleryProvider",
    "GelbooruLiveProvider",
    "LegacyProviderAdapter",
    "LiveProviderRegistry",
    "OpaqueCursorCodec",
    "PeriodSemantics",
    "ProviderCapabilities",
    "ProviderError",
    "ProviderPage",
    "ProviderPayloadError",
    "ProviderRequestError",
    "ProviderRuntime",
    "Source",
    "View",
    "V2_API_ROOT",
    "V53FeatureFlags",
    "YandereLiveProvider",
    "all_provider_capabilities",
    "autocomplete_client_query_key",
    "browse_client_query_key",
    "build_live_provider_registry",
    "create_v2_handlers",
    "create_feature_handler",
    "error_envelope",
    "facet_client_query_key",
    "get_provider_capabilities",
    "get_default_cursor_codec",
    "page_key",
    "load_v53_feature_flags",
    "register_feature_route",
    "register_v2_routes",
    "success_envelope",
    "validate_autocomplete_request",
    "validate_browse_request",
    "validate_facet_request",
]
